#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <cassert>
#include <memory>
#include <bitset>
#include <array>
#include <vector>
#include <unordered_map>
#include <fstream>
#include <mutex>
#include <chrono>
#include <cmath>
#include <limits>
#include <algorithm>